/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HealthRouteImport } from './routes/health'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlansIndexRouteImport } from './routes/plans/index'
import { Route as PlansPlanIdRouteImport } from './routes/plans/$planId'
import { Route as PlansPlanIdIndexRouteImport } from './routes/plans/$planId/index'
import { Route as PlansPlanIdRecurringExpensesRouteImport } from './routes/plans/$planId/recurring-expenses'
import { Route as PlansPlanIdPaymentPeriodsRouteImport } from './routes/plans/$planId/payment-periods'
import { Route as PlansPlanIdIncomeRouteImport } from './routes/plans/$planId/income'
import { Route as PlansPlanIdCategoriesRouteImport } from './routes/plans/$planId/categories'
import { Route as PlansPlanIdAccountsRouteImport } from './routes/plans/$planId/accounts'
import { Route as PlansPlanIdPaymentPeriodsIndexRouteImport } from './routes/plans/$planId/payment-periods/index'
import { Route as PlansPlanIdPaymentPeriodsPeriodIdRouteImport } from './routes/plans/$planId/payment-periods/$periodId'

const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansIndexRoute = PlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansPlanIdRoute = PlansPlanIdRouteImport.update({
  id: '/plans/$planId',
  path: '/plans/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansPlanIdIndexRoute = PlansPlanIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlansPlanIdRoute,
} as any)
const PlansPlanIdRecurringExpensesRoute =
  PlansPlanIdRecurringExpensesRouteImport.update({
    id: '/recurring-expenses',
    path: '/recurring-expenses',
    getParentRoute: () => PlansPlanIdRoute,
  } as any)
const PlansPlanIdPaymentPeriodsRoute =
  PlansPlanIdPaymentPeriodsRouteImport.update({
    id: '/payment-periods',
    path: '/payment-periods',
    getParentRoute: () => PlansPlanIdRoute,
  } as any)
const PlansPlanIdIncomeRoute = PlansPlanIdIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => PlansPlanIdRoute,
} as any)
const PlansPlanIdCategoriesRoute = PlansPlanIdCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => PlansPlanIdRoute,
} as any)
const PlansPlanIdAccountsRoute = PlansPlanIdAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => PlansPlanIdRoute,
} as any)
const PlansPlanIdPaymentPeriodsIndexRoute =
  PlansPlanIdPaymentPeriodsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PlansPlanIdPaymentPeriodsRoute,
  } as any)
const PlansPlanIdPaymentPeriodsPeriodIdRoute =
  PlansPlanIdPaymentPeriodsPeriodIdRouteImport.update({
    id: '/$periodId',
    path: '/$periodId',
    getParentRoute: () => PlansPlanIdPaymentPeriodsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/plans/$planId': typeof PlansPlanIdRouteWithChildren
  '/plans/': typeof PlansIndexRoute
  '/plans/$planId/accounts': typeof PlansPlanIdAccountsRoute
  '/plans/$planId/categories': typeof PlansPlanIdCategoriesRoute
  '/plans/$planId/income': typeof PlansPlanIdIncomeRoute
  '/plans/$planId/payment-periods': typeof PlansPlanIdPaymentPeriodsRouteWithChildren
  '/plans/$planId/recurring-expenses': typeof PlansPlanIdRecurringExpensesRoute
  '/plans/$planId/': typeof PlansPlanIdIndexRoute
  '/plans/$planId/payment-periods/$periodId': typeof PlansPlanIdPaymentPeriodsPeriodIdRoute
  '/plans/$planId/payment-periods/': typeof PlansPlanIdPaymentPeriodsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/plans': typeof PlansIndexRoute
  '/plans/$planId/accounts': typeof PlansPlanIdAccountsRoute
  '/plans/$planId/categories': typeof PlansPlanIdCategoriesRoute
  '/plans/$planId/income': typeof PlansPlanIdIncomeRoute
  '/plans/$planId/recurring-expenses': typeof PlansPlanIdRecurringExpensesRoute
  '/plans/$planId': typeof PlansPlanIdIndexRoute
  '/plans/$planId/payment-periods/$periodId': typeof PlansPlanIdPaymentPeriodsPeriodIdRoute
  '/plans/$planId/payment-periods': typeof PlansPlanIdPaymentPeriodsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/plans/$planId': typeof PlansPlanIdRouteWithChildren
  '/plans/': typeof PlansIndexRoute
  '/plans/$planId/accounts': typeof PlansPlanIdAccountsRoute
  '/plans/$planId/categories': typeof PlansPlanIdCategoriesRoute
  '/plans/$planId/income': typeof PlansPlanIdIncomeRoute
  '/plans/$planId/payment-periods': typeof PlansPlanIdPaymentPeriodsRouteWithChildren
  '/plans/$planId/recurring-expenses': typeof PlansPlanIdRecurringExpensesRoute
  '/plans/$planId/': typeof PlansPlanIdIndexRoute
  '/plans/$planId/payment-periods/$periodId': typeof PlansPlanIdPaymentPeriodsPeriodIdRoute
  '/plans/$planId/payment-periods/': typeof PlansPlanIdPaymentPeriodsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/plans/$planId'
    | '/plans/'
    | '/plans/$planId/accounts'
    | '/plans/$planId/categories'
    | '/plans/$planId/income'
    | '/plans/$planId/payment-periods'
    | '/plans/$planId/recurring-expenses'
    | '/plans/$planId/'
    | '/plans/$planId/payment-periods/$periodId'
    | '/plans/$planId/payment-periods/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/plans'
    | '/plans/$planId/accounts'
    | '/plans/$planId/categories'
    | '/plans/$planId/income'
    | '/plans/$planId/recurring-expenses'
    | '/plans/$planId'
    | '/plans/$planId/payment-periods/$periodId'
    | '/plans/$planId/payment-periods'
  id:
    | '__root__'
    | '/'
    | '/health'
    | '/plans/$planId'
    | '/plans/'
    | '/plans/$planId/accounts'
    | '/plans/$planId/categories'
    | '/plans/$planId/income'
    | '/plans/$planId/payment-periods'
    | '/plans/$planId/recurring-expenses'
    | '/plans/$planId/'
    | '/plans/$planId/payment-periods/$periodId'
    | '/plans/$planId/payment-periods/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  PlansPlanIdRoute: typeof PlansPlanIdRouteWithChildren
  PlansIndexRoute: typeof PlansIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/': {
      id: '/plans/'
      path: '/plans'
      fullPath: '/plans/'
      preLoaderRoute: typeof PlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/$planId': {
      id: '/plans/$planId'
      path: '/plans/$planId'
      fullPath: '/plans/$planId'
      preLoaderRoute: typeof PlansPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/$planId/': {
      id: '/plans/$planId/'
      path: '/'
      fullPath: '/plans/$planId/'
      preLoaderRoute: typeof PlansPlanIdIndexRouteImport
      parentRoute: typeof PlansPlanIdRoute
    }
    '/plans/$planId/recurring-expenses': {
      id: '/plans/$planId/recurring-expenses'
      path: '/recurring-expenses'
      fullPath: '/plans/$planId/recurring-expenses'
      preLoaderRoute: typeof PlansPlanIdRecurringExpensesRouteImport
      parentRoute: typeof PlansPlanIdRoute
    }
    '/plans/$planId/payment-periods': {
      id: '/plans/$planId/payment-periods'
      path: '/payment-periods'
      fullPath: '/plans/$planId/payment-periods'
      preLoaderRoute: typeof PlansPlanIdPaymentPeriodsRouteImport
      parentRoute: typeof PlansPlanIdRoute
    }
    '/plans/$planId/income': {
      id: '/plans/$planId/income'
      path: '/income'
      fullPath: '/plans/$planId/income'
      preLoaderRoute: typeof PlansPlanIdIncomeRouteImport
      parentRoute: typeof PlansPlanIdRoute
    }
    '/plans/$planId/categories': {
      id: '/plans/$planId/categories'
      path: '/categories'
      fullPath: '/plans/$planId/categories'
      preLoaderRoute: typeof PlansPlanIdCategoriesRouteImport
      parentRoute: typeof PlansPlanIdRoute
    }
    '/plans/$planId/accounts': {
      id: '/plans/$planId/accounts'
      path: '/accounts'
      fullPath: '/plans/$planId/accounts'
      preLoaderRoute: typeof PlansPlanIdAccountsRouteImport
      parentRoute: typeof PlansPlanIdRoute
    }
    '/plans/$planId/payment-periods/': {
      id: '/plans/$planId/payment-periods/'
      path: '/'
      fullPath: '/plans/$planId/payment-periods/'
      preLoaderRoute: typeof PlansPlanIdPaymentPeriodsIndexRouteImport
      parentRoute: typeof PlansPlanIdPaymentPeriodsRoute
    }
    '/plans/$planId/payment-periods/$periodId': {
      id: '/plans/$planId/payment-periods/$periodId'
      path: '/$periodId'
      fullPath: '/plans/$planId/payment-periods/$periodId'
      preLoaderRoute: typeof PlansPlanIdPaymentPeriodsPeriodIdRouteImport
      parentRoute: typeof PlansPlanIdPaymentPeriodsRoute
    }
  }
}

interface PlansPlanIdPaymentPeriodsRouteChildren {
  PlansPlanIdPaymentPeriodsPeriodIdRoute: typeof PlansPlanIdPaymentPeriodsPeriodIdRoute
  PlansPlanIdPaymentPeriodsIndexRoute: typeof PlansPlanIdPaymentPeriodsIndexRoute
}

const PlansPlanIdPaymentPeriodsRouteChildren: PlansPlanIdPaymentPeriodsRouteChildren =
  {
    PlansPlanIdPaymentPeriodsPeriodIdRoute:
      PlansPlanIdPaymentPeriodsPeriodIdRoute,
    PlansPlanIdPaymentPeriodsIndexRoute: PlansPlanIdPaymentPeriodsIndexRoute,
  }

const PlansPlanIdPaymentPeriodsRouteWithChildren =
  PlansPlanIdPaymentPeriodsRoute._addFileChildren(
    PlansPlanIdPaymentPeriodsRouteChildren,
  )

interface PlansPlanIdRouteChildren {
  PlansPlanIdAccountsRoute: typeof PlansPlanIdAccountsRoute
  PlansPlanIdCategoriesRoute: typeof PlansPlanIdCategoriesRoute
  PlansPlanIdIncomeRoute: typeof PlansPlanIdIncomeRoute
  PlansPlanIdPaymentPeriodsRoute: typeof PlansPlanIdPaymentPeriodsRouteWithChildren
  PlansPlanIdRecurringExpensesRoute: typeof PlansPlanIdRecurringExpensesRoute
  PlansPlanIdIndexRoute: typeof PlansPlanIdIndexRoute
}

const PlansPlanIdRouteChildren: PlansPlanIdRouteChildren = {
  PlansPlanIdAccountsRoute: PlansPlanIdAccountsRoute,
  PlansPlanIdCategoriesRoute: PlansPlanIdCategoriesRoute,
  PlansPlanIdIncomeRoute: PlansPlanIdIncomeRoute,
  PlansPlanIdPaymentPeriodsRoute: PlansPlanIdPaymentPeriodsRouteWithChildren,
  PlansPlanIdRecurringExpensesRoute: PlansPlanIdRecurringExpensesRoute,
  PlansPlanIdIndexRoute: PlansPlanIdIndexRoute,
}

const PlansPlanIdRouteWithChildren = PlansPlanIdRoute._addFileChildren(
  PlansPlanIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  PlansPlanIdRoute: PlansPlanIdRouteWithChildren,
  PlansIndexRoute: PlansIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
